apiVersion: batch/v1
kind: Job
metadata:
  name: wscraper-job
  namespace: scraping
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true" 
    spec:
      serviceAccountName: scrape-service-account
      restartPolicy: Never
      # Optional: ensure it never tries a GPU node
      nodeSelector:
        cloud.google.com/gke-nodepool: cpu-pool
      containers:
      - name: buzz-scraper
        image: us-east4-docker.pkg.dev/amlc-449423/amlcfinalproject/buzz-scraper:latest
        env:
        - name: podcast-chiclets
          value: /mnt/gcs
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: podcast-chiclets
          mountPath: /mnt/gcs
      volumes:
      - name: podcast-chiclets
        csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: false
          volumeAttributes:
            bucketName: podcast-chiclets
            mountOptions: "implicit-dirs"  